apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: thirdeye

resources:
  - 20-postgres.yaml
  - 30-application.yaml

configMapGenerator:
  - name: thirdeye-db-init-script
    files:
      - 00_create_user.sh=db-00-create-user.sh
      - 01_schema.sql=db-01-schema.sql
      - 02_init_data.sql=db-02-init-data.sql
      - 99_reassign_owner.sh=db-99-reassign-owner.sh

generatorOptions:
  disableNameSuffixHash: true
